#planner stage
ARG     TAG=dev@sha256:0644a38a7d0a408ebc276815ebbd786eccc98e4b3903266abb9ef9e7bb9e3d11
FROM    hyperledger/iroha2-base:$TAG AS planner
WORKDIR /iroha
COPY    . .
RUN     cargo chef prepare --recipe-path recipe.json

# chef stage
FROM planner as keeper
COPY --from=planner /iroha/recipe.json recipe.json
RUN  cargo chef cook --profile deploy --target x86_64-unknown-linux-musl --features vendored --recipe-path recipe.json
